export const FETCH_IMAGES_REQUEST = "FETCH_IMAGES_REQUEST";
export const FETCH_IMAGES_SUCCESS = "FETCH_IMAGES_SUCCESS";
export const FETCH_IMAGES_FAILURE = "FETCH_IMAGES_FAILURE";
export const SET_TOP_TEXT = "SET_TOP_TEXT";
export const SET_BOTTOM_TEXT = "SET_BOTTOM_TEXT";
export const SET_MEME_IMAGE = "SET_MEME_IMAGE";
